export default function AboutPage() {
  return (
    <div className="pt-32 pb-24 px-4 min-h-screen bg-gradient-to-b from-vesper-white to-vesper-mist">
      <div className="max-w-3xl mx-auto">
        
        <div className="text-center mb-16">
          <h1 className="font-display text-5xl md:text-6xl text-vesper-navy mb-6">
            About Vesper
          </h1>
        </div>

        <section className="mb-16">
          <div className="prose prose-lg max-w-none space-y-6 text-vesper-dark leading-relaxed">
            <p>
              The artwork is called Vesper. It lives on the chain. It takes the oldest human act—the 
              prayer—and fixes it in light. People send their words from a website or from X. An 
              intelligence turns each one into something lean and clear, almost ancient. The words are 
              then cast onto water—on rain, on mist, on snow. They drift and vanish. You can watch 
              them rising all night on a livestream, like breath leaving the world.
            </p>
            <p>
              Each prayer is kept forever in the ledger, written not for profit or praise, but as a 
              trace of longing. No one owns them. Everyone can see them. The VSPR token—nine hundred 
              ninety-nine thousand, nine hundred ninety-nine of them—marks not possession, but care. 
              It belongs to those who keep the stream and the light alive.
            </p>
            <p>
              Vesper imagines a planet whispering—prayers falling on Angel Falls, rain in Tokyo, snow 
              in the Arctic. Some are real, some are dream-water made by machines. All dissolve as they 
              should. This is the work: not to hold, but to release. To watch light go out on the skin 
              of water, and to know it endures somewhere, unseen.
            </p>
          </div>
        </section>

        <section className="mb-16">
          <h2 className="font-display text-3xl text-vesper-navy mb-6">The Pipeline</h2>
          <div className="space-y-4 text-vesper-dark leading-relaxed">
            <p>
              Prayers arrive from X.com or a website form. Each passes through Grok, which translates 
              them into a stoic tone—stripping away desperation, replacing it with calm resolve and 
              lyrical beauty. The transformed prayer is posted to X.com and written permanently to 
              the Solana blockchain.
            </p>
            <p>
              From there, it enters the projection system. TouchDesigner renders the words in light 
              and casts them onto water environments—some real, some generated by AI. The stream 
              runs continuously on YouTube and pump.fun, 24 hours a day. The backdrop rotates daily: 
              Angel Falls one night, misty mountains the next, rain falling in Tokyo after that.
            </p>
          </div>
        </section>

        <section className="mb-16">
          <h2 className="font-display text-3xl text-vesper-navy mb-6">Physical Installations</h2>
          <div className="text-vesper-dark leading-relaxed">
            <p>
              Beyond the digital stream, Vesper will exist as 4 to 6 physical installations at venues 
              across the globe. In these spaces, prayers are projected with real light onto actual 
              water—evaporating water, still pools, falling rain, snow, and mist. As the words dissolve 
              into the water, they appear to rise and dissipate into the sky above.
            </p>
            <p className="mt-4 text-vesper-grey italic">
              Installation dates and locations to be announced.
            </p>
          </div>
        </section>
 <section className="mb-16">
          <h2 className="font-display text-3xl text-vesper-navy mb-6">Artist</h2>
          <div className="text-vesper-dark leading-relaxed space-y-4">
            <p>
              Vesper was created by Megan Murphy, an artist working where technology meets spirit 
              and memory. For over twenty-five years, her work has traced the sacred in the 
              everyday—shown in Portland, Seattle, New York, and held in museum collections across 
              the country.
            </p>
            <p>
              Murphy's work weaves medieval light with modern code. She lives in Idaho with her 
              children, Murphy Kendall and Bastian Lengyel. Vesper is her meditation on how the 
              sacred is visualized in a digital world.
            </p>
          </div>
        </section>
        <section>
          <h2 className="font-display text-3xl text-vesper-navy mb-6">Contact</h2>
          <div className="text-vesper-dark">
            <p className="mb-4">For press, partnership, or venue inquiries:</p>
            <a 
              href="https://x.com/vesper" 
              target="_blank" 
              rel="noopener noreferrer"
              className="text-vesper-blue hover:text-vesper-navy transition-colors"
            >
              @vesper on X.com
            </a>
          </div>
        </section>

      </div>
    </div>
  )
}